from __future__ import annotations

from dataclasses import dataclass
from pathlib import PurePosixPath


@dataclass(frozen=True)
class PathDecision:
    action: str
    reason: str = ""

    @property
    def included(self) -> bool:
        return self.action == "include"


class PathPolicy:
    """Classify repository paths consistently across profiling and mining."""

    HARD_EXCLUDED_DIRS = frozenset(
        {
            ".git",
            ".hg",
            ".svn",
            ".venv",
            "venv",
            "env",
            "node_modules",
            "vendor",
            "third_party",
            "third-party",
            "external",
            "extern",
            "build",
            "dist",
            "out",
            "__pycache__",
            ".pytest_cache",
            ".mypy_cache",
            ".ruff_cache",
            ".gradle",
            ".idea",
        }
    )
    LOW_PRIORITY_DIRS = frozenset(
        {
            "test",
            "tests",
            "testing",
            "__test__",
            "__tests__",
            "spec",
            "specs",
            "example",
            "examples",
            "sample",
            "samples",
            "demo",
            "demos",
            "benchmark",
            "benchmarks",
            "bench",
            "fuzz",
            "fuzzing",
            "fixtures",
            "mocks",
            "docs",
            "doc",
        }
    )
    GENERATED_DIRS = frozenset({"generated", "__generated__", "autogenerated", "codegen"})
    GENERATED_SUFFIXES = (
        ".min.js",
        ".min.css",
        ".bundle.js",
        ".bundle.css",
        ".js.map",
        ".css.map",
        ".pb.go",
        ".pb.cc",
        ".pb.h",
        ".generated.py",
        ".generated.js",
        ".generated.ts",
    )

    def classify(self, path: str) -> PathDecision:
        normalized = path.replace("\\", "/").strip("/")
        if not normalized:
            return PathDecision("include")
        pure = PurePosixPath(normalized)
        parts = tuple(part.lower() for part in pure.parts)
        name = pure.name.lower()

        excluded = next((part for part in parts[:-1] if part in self.HARD_EXCLUDED_DIRS), "")
        if excluded:
            return PathDecision("exclude", f"excluded_directory:{excluded}")
        generated_dir = next((part for part in parts[:-1] if part in self.GENERATED_DIRS), "")
        if generated_dir:
            return PathDecision("exclude", f"generated_directory:{generated_dir}")
        if name.endswith(self.GENERATED_SUFFIXES):
            return PathDecision("exclude", "generated_or_minified_file")
        if name.startswith(("jquery.min.", "bootstrap.min.")):
            return PathDecision("exclude", "minified_library")

        low_priority = next((part for part in parts[:-1] if part in self.LOW_PRIORITY_DIRS), "")
        if low_priority:
            return PathDecision("deprioritize", f"low_priority_directory:{low_priority}")
        if "static" in parts[:-1] and "vendor" in parts[:-1]:
            return PathDecision("exclude", "vendored_static_asset")
        return PathDecision("include")

    def include_inventory(self, path: str) -> bool:
        decision = self.classify(path)
        return decision.action != "exclude"

    def include_source(self, path: str, *, allow_low_priority: bool = False) -> bool:
        decision = self.classify(path)
        return decision.action == "include" or (allow_low_priority and decision.action == "deprioritize")
